### ISSUE TITLE
None of the links in README lead to tutorials

### ISSUE THREAD

**Issue by scout208** [Azure-Samples/iot-remote-monitoring-c-raspberrypi-getstartedkit#9]
All the links just end up going to https://docs.microsoft.com/en-us/azure/iot-suite/. I expected that they would lead to actual step-by-step tutorials for each of the ones suggested. This is pretty misleading. These links should probably either be updated to point to the correct tutorials or removed completely.

**Comment by dominicbetts** [comment]
Hi @scout208 - I fixed the links. Note that these samples are for the previous version of the Remote Monitoring solution accelerator.

You can find samples for the current version here: https://github.com/Azure/azure-iot-sdk-c/tree/master/samples/solutions/remote_monitoring_client
